### PR TITLE
Adding test to rerender component in route-less engine

### PR DESCRIPTION
**Pull request by pete-the-pete**
Created a failing test to exhibit #126

### CODE REVIEW

**Comment by dgeb** [comment]
@pete-the-pete thanks - will investigate soon.

**Comment by pete-the-pete** [comment]
@thousand has a fix and will have a PR soon

**Comment by thousand** [comment]
Just saw this, will include these tests in my PR, #138 too.

**Comment by dgeb** [comment]
Included in (and fixed via) #142. Thanks @pete-the-pete!

**Pull request closed without merging**
