### PR TITLE
[EE-231] Symlink Failure - Directory Name resolution

### PR DESCRIPTION
**Pull request by ooluwadiya**
[EE-231] Changing Rollup Funnel to use Path-Posix library for cross-OS compatibility

### CODE REVIEW

**Comment by trentmwillis** [comment]
You'll need to add `path-posix` to the `package.json` `dependencies` as well.

**Comment by nathanhammond** [comment]
I'm pretty sure I didn't write any tests for that portion of code because I'm a terrible person. I need to manually confirm that this still works on POSIX environments before landing.

**Comment by nathanhammond** [comment]
Scumbag @nathanhammond who didn't write automated tests for the build step has completed his tests and can confirm that this works.

**Comment by ooluwadiya** [comment]
Hahahahahaha @nathanhammond ... You are forgiven 😀

**Pull request merged**
