### PR TITLE
Upstream resolver changes

### PR DESCRIPTION
**Pull request by trentmwillis**
Dependent on: https://github.com/ember-cli/ember-resolver/pull/151.

Also, starts testing against the Beta branch of Ember. Figured we should probably do that if 2.8 is supposed to be compatible with Engines.

Closes: #10

### CODE REVIEW

**Comment by trentmwillis** [comment]
@dgeb and @rwjblue this is passing in Beta, but Canary is failing due to a build issue. Dug into it a bit, but couldn't figure it out. Seems potentially similar to this old issue: https://github.com/emberjs/ember.js/issues/13347

**Comment by trentmwillis** [comment]
Failure seems to have resolved itself. I think this should be good to merge.

**Comment by chadhietala** [comment]
LGTM

**Comment by dgeb** [comment]
Thanks @trentmwillis :shipit:

**Pull request merged**
