### PR TITLE
Fix Ember.merge deprecations

### PR DESCRIPTION
**Pull request by trentmwillis**
Addressing #79.

### CODE REVIEW

**Comment by dgeb** [comment]
Thanks again @trentmwillis!

**Comment by rwjblue** [comment]
FYI - This deprecation has been removed from canary/beta/release and will be released as 2.5.1 sometime Monday.

**Comment by trentmwillis** [comment]
@rwjblue interesting, looking at the [PR to turn it off](https://github.com/emberjs/ember.js/pull/13344), sounds like it will still be turned back on in a future release though, correct? The ecosystem just isn't ready for it to be deprecated right now.

**Comment by rwjblue** [comment]
@trentmwillis - Yep, I was definitely not suggesting that this PR was invalid or anything.  I'm mostly just pointing out, that many many things are spewing this deprecation at the moment so we decided to disable.

**Pull request merged**
