### PR TITLE
Don't use rollup-funnel for non-lazy builds

### PR DESCRIPTION
**Pull request by trentmwillis**
Improves build and re-build performance.

cc @nathanhammond

### CODE REVIEW

**Comment by nathanhammond** [comment]
Looking at this now I'm unsure why this code path exists. We may find out later, but it seems safe to remove to me. :shipit:

**Comment by trentmwillis** [comment]
Hoping it was just an oversight from being too close to the problem when it was originally written. Should we test against your test app?

**Comment by nathanhammond** [comment]
I'm in the process of doing that to confirm all things look good.

**Comment by nathanhammond** [comment]
(Reasonable order of operations: who needs it?)

**Pull request merged**
