### PR TITLE
Document how to tests in-repo engines components.

### PR DESCRIPTION
**Pull request by abuiles**

### CODE REVIEW

**Comment by knownasilya** [comment]
So there is no way to test the component in the engine?

**Comment by abuiles** [comment]
@knownasilya probably depends on https://github.com/ember-cli/rfcs/pull/60

**Comment by rwjblue** [comment]
@knownasilya - For in-repo engines, no not really.  This documentation isn't really about stand alone engines.

**Comment by jherdman** [comment]
I hate to resurrect this issue a bit, but I found that this was necessary for me to integration test my helpers and components.

**Pull request merged**
